import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Applicaçao de Eventos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header class={styles.headerMain}>
          <Link href='/' >Logo</Link>
          <nav>
            <Link  passHref href='/' >Home</Link>
            <Link passHref href='/events' >Eventos</Link>
            <Link passHref href='/about-us' >Sobre</Link>
          </nav>

        </header>   
           <main className={styles.main}>
            {data.map(ev =>
              <Link passHref className={styles.box} key={ev.id} href={`/events/${ev.id}`} >
                <Image alt={ev.title} height={400} width={400} src={ev.image} />
                <h2> {ev.title} </h2>
                <p> {ev.description} </p>
              </Link>
              )}
            </main>
        <footer class={styles.footer}>
           <p> &copy; Websoluções num turial com </p>
        </footer>

    </>
  )
}

export async function getServerSideProps(){
  const {events_categories} = await import ("../data/date.json")
  console.log(events_categories)
     return{
       props:{
         data: events_categories,
       }
     };
}